/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlnt.ui;

import com.qlnt.dao.NhanVienDAO;
import com.qlnt.entity.NhanVien;
import com.qlnt.util.Auth;
import com.qlnt.util.MsgBox;
import com.qlnt.util.XImage;
import java.awt.Cursor;
import static java.awt.Frame.HAND_CURSOR;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author monst
 */
public class DangNhapJFrame extends javax.swing.JFrame {

    /**
     * Creates new form DangNhapJFrame
     */
    public DangNhapJFrame() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblPassword = new javax.swing.JLabel();
        btnEye = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        btnLogin = new javax.swing.JLabel();
        btnCancel = new javax.swing.JLabel();
        lblQuanlynhathuoc = new javax.swing.JLabel();
        btnMinus = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnForget = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(760, 580));
        setMinimumSize(new java.awt.Dimension(760, 580));
        setUndecorated(true);
        setOpacity(0.0F);
        setPreferredSize(new java.awt.Dimension(760, 580));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Tên đăng nhập");
        getContentPane().add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, -1));

        txtUsername.setBackground(new java.awt.Color(28, 40, 89));
        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setText("phucnh");
        txtUsername.setBorder(null);
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 250, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 260, 20));

        lblPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Mật khẩu");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, -1, -1));

        btnEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlnt/icon/hidePass.png"))); // NOI18N
        btnEye.setBorder(null);
        btnEye.setBorderPainted(false);
        btnEye.setContentAreaFilled(false);
        btnEye.setDefaultCapable(false);
        btnEye.setFocusPainted(false);
        btnEye.setFocusable(false);
        btnEye.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEyeMouseEntered(evt);
            }
        });
        btnEye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEyeActionPerformed(evt);
            }
        });
        getContentPane().add(btnEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 40, 30));

        txtPassword.setBackground(new java.awt.Color(28, 40, 89));
        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setText("123");
        txtPassword.setBorder(null);
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 220, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 260, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlnt/icon/Login.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, -1));

        lblLogin.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setText("ĐĂNG NHẬP");
        getContentPane().add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, -1, -1));

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlnt/icon/btnLogin.png"))); // NOI18N
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, -1, -1));

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlnt/icon/btnCancel.png"))); // NOI18N
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelMouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCancelMouseReleased(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, -1, -1));

        lblQuanlynhathuoc.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblQuanlynhathuoc.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanlynhathuoc.setText("QUẢN LÝ NHÀ THUỐC");
        getContentPane().add(lblQuanlynhathuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        btnMinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlnt/icon/minus.png"))); // NOI18N
        btnMinus.setBorder(null);
        btnMinus.setBorderPainted(false);
        btnMinus.setContentAreaFilled(false);
        btnMinus.setFocusPainted(false);
        btnMinus.setFocusable(false);
        btnMinus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinusMouseExited(evt);
            }
        });
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });
        getContentPane().add(btnMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlnt/icon/close.png"))); // NOI18N
        btnClose.setBorder(null);
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setDefaultCapable(false);
        btnClose.setFocusPainted(false);
        btnClose.setFocusable(false);
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, -1, -1));

        btnForget.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnForget.setForeground(new java.awt.Color(255, 255, 255));
        btnForget.setText("Quên mật khẩu?");
        btnForget.setBorder(null);
        btnForget.setBorderPainted(false);
        btnForget.setContentAreaFilled(false);
        btnForget.setDefaultCapable(false);
        btnForget.setFocusPainted(false);
        btnForget.setFocusable(false);
        btnForget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnForgetMouseEntered(evt);
            }
        });
        btnForget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgetActionPerformed(evt);
            }
        });
        getContentPane().add(btnForget, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlnt/icon/LOGO.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlnt/icon/background.png"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnEyeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEyeMouseEntered
        btnEye.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_btnEyeMouseEntered

    private void btnEyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEyeActionPerformed
        showHidePassword();
    }//GEN-LAST:event_btnEyeActionPerformed

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        dangnhap();
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        btnLogin.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited

    }//GEN-LAST:event_btnLoginMouseExited

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnCancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelMouseReleased

    private void btnMinusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinusMouseEntered
        changeIcon(1, btnMinus, "src//com//qlnt//icon//minus_hover.png");

    }//GEN-LAST:event_btnMinusMouseEntered

    private void btnMinusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinusMouseExited
        changeIcon(2, btnMinus, "src//com//qlnt//icon//minus.png");

    }//GEN-LAST:event_btnMinusMouseExited

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        minus();
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        changeIcon(1, btnClose, "src//com//qlnt//icon//close_hover.png");
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        changeIcon(2, btnClose, "src//com//qlnt//icon//close.png");
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        close();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnForgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgetActionPerformed
        openQuenMK();
    }//GEN-LAST:event_btnForgetActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        loadOpenForm();
    }//GEN-LAST:event_formWindowOpened

    private void btnForgetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnForgetMouseEntered
        btnForget.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_btnForgetMouseEntered

    private void btnCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseEntered
        btnCancel.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_btnCancelMouseEntered

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusGained
        if(txtUsername.getText().equals("Nhập mã nhân viên")){
            txtUsername.setText("");
        }
    }//GEN-LAST:event_txtUsernameFocusGained

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusLost
        if(txtUsername.getText().equals("")){
            txtUsername.setText("Nhập mã nhân viên");
        }
    }//GEN-LAST:event_txtUsernameFocusLost

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        if(new String(txtPassword.getText()).equals("Nhập mật khẩu")){
            txtPassword.setText("");
        }
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        if(new String(txtPassword.getText()).equals("")){
            txtPassword.setText("Nhập mật khẩu");
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        dangnhap();
    }//GEN-LAST:event_txtPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhapJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancel;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnEye;
    private javax.swing.JButton btnForget;
    private javax.swing.JLabel btnLogin;
    private javax.swing.JButton btnMinus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblQuanlynhathuoc;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
    void init() {
        setLocationRelativeTo(this);
        txtUsername.setText("Nhập mã nhân viên");
        txtPassword.setText("Nhập mật khẩu");
        XImage.getAppIcon();
        setIconImage(XImage.getAppIcon());
    }

    void close() {
        System.exit(0);
    }

    void openQuenMK() {
        new QuenMatKhauJDialog(this, true).setVisible(true);
    }

    private void loadOpenForm() {
        for (double i = 0.0; i < 1.0; i = i + 0.1) {
            String val = i + "";
            float f = Float.parseFloat(val);
            this.setOpacity(f);
            try {
                Thread.sleep(70);
            } catch (Exception e) {
            }
        }
    }

    private void minus() {
        this.setState(1);
    }

    void changeIcon(int so, JButton btn, String url) {
        if (so == 1) {
            Image img = getToolkit().createImage(url);
            btn.setIcon(new ImageIcon(img));
            btn.setCursor(new Cursor(HAND_CURSOR));
        } else {
            Image img = getToolkit().createImage(url);
            btn.setIcon(new ImageIcon(img));
        }
    }

    int showHidePass = 1;

    private void showHidePassword() {
        showHidePass++;
        if (showHidePass % 2 == 0) {
            Image img = getToolkit().createImage("src//com//qlnt//icon//showpass.png");
            btnEye.setIcon(new ImageIcon(img));
            txtPassword.setEchoChar((char) 0);
        } else {
            Image img = getToolkit().createImage("src//com//qlnt//icon//hidePass.png");
            btnEye.setIcon(new ImageIcon(img));
            txtPassword.setEchoChar('\u25cf');
        }
    }

    boolean kiemtra() {
        if (txtUsername.getText().equals("")) {
            MsgBox.alert(this, "Vui lòng nhập tên đăng nhập");
            return false;
        } else if (new String(txtPassword.getPassword()).equals("")) {
            MsgBox.alert(this, "Vui lòng nhập mật khẩu đăng nhập");
            return false;
        }
        return true;
    }

    NhanVienDAO dao = new NhanVienDAO();

    void dangnhap() {
        if (kiemtra()) {
            String username = txtUsername.getText();
            String password = new String(txtPassword.getPassword());
            NhanVien nv = dao.selectById(username);            
            if (nv == null) {
                MsgBox.alert(this, "Sai tên đăng nhập");
            } else if (!password.equals(nv.getMatKhau())) {
                MsgBox.alert(this, "Sai mật khẩu");
            } else {
                MsgBox.alert(this, "Đăng nhập thành công");
                Auth.user = nv;
                new QuanLyNhaThuocJFrame().setVisible(true);
                this.dispose();
            }
        }
    }
}
