/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlnt.ui;

import com.qlnt.dao.NhanVienDAO;
import com.qlnt.entity.NhanVien;
import com.qlnt.util.MsgBox;
import java.util.Date;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;

/**
 *
 * @author monst
 */
public class QuenMatKhauJDialog extends javax.swing.JDialog {

    /**
     * Creates new form DangNhapJDialog
     */
    public QuenMatKhauJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsername = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblLogin = new javax.swing.JLabel();
        btnTiepTuc = new javax.swing.JLabel();
        btnThoat = new javax.swing.JLabel();
        lblQuanlynhathuoc = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(760, 580));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Email:");
        getContentPane().add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, -1));

        txtEmail.setBackground(new java.awt.Color(28, 40, 89));
        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(null);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 250, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 260, 20));

        lblLogin.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setText("QUÊN MẬT KHẨU");
        getContentPane().add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, -1));

        btnTiepTuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlnt/icon/btnTiepTuc.png"))); // NOI18N
        btnTiepTuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTiepTucMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTiepTucMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTiepTucMouseExited(evt);
            }
        });
        getContentPane().add(btnTiepTuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, -1));

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlnt/icon/btnThoat1.png"))); // NOI18N
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThoatMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnThoatMouseReleased(evt);
            }
        });
        getContentPane().add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, -1, -1));

        lblQuanlynhathuoc.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblQuanlynhathuoc.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanlynhathuoc.setText("QUẢN LÝ NHÀ THUỐC");
        getContentPane().add(lblQuanlynhathuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlnt/icon/close.png"))); // NOI18N
        btnClose.setBorder(null);
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setDefaultCapable(false);
        btnClose.setFocusPainted(false);
        btnClose.setFocusable(false);
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, -1, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlnt/icon/background.png"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnTiepTucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTiepTucMouseClicked
        quenMatKhau();
    }//GEN-LAST:event_btnTiepTucMouseClicked

    private void btnTiepTucMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTiepTucMouseEntered

    }//GEN-LAST:event_btnTiepTucMouseEntered

    private void btnTiepTucMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTiepTucMouseExited

    }//GEN-LAST:event_btnTiepTucMouseExited

    private void btnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseClicked
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_btnThoatMouseClicked

    private void btnThoatMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThoatMouseReleased

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
//        changeIcon(1, btnClose, "src//Icon//closeGray.png");
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
//        changeIcon(2, btnClose, "src//Icon//close.png");
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        close();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuenMatKhauJDialog dialog = new QuenMatKhauJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel btnThoat;
    private javax.swing.JLabel btnTiepTuc;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblQuanlynhathuoc;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
    void init() {
        setLocationRelativeTo(this);
    }

    void close() {
        this.dispose();
    }
    NhanVienDAO nvdao = new NhanVienDAO();

    private void quenMatKhau() {
        String email = txtEmail.getText();
        NhanVien nv = nvdao.selectByEmail(email);
        System.out.println(email);
        if (email.equals("")) {
            MsgBox.alert(this, "Vui lòng nhập Email");
        } else if (nv==null) {
            MsgBox.alert(this, "Không tìm thấy nhân viên có mail: \n"
                    + email);
        } else {
            try {
                Properties p = new Properties();
                p.put("mail.smtp.auth", "true");
                p.put("mail.smtp.starttls.enable", "true");
                p.put("mail.smtp.host", "smtp.gmail.com");
                p.put("mail.smtp.port", 587);
                String username = "phucnhps19246@fpt.edu.vn";
                String Password = "Phuc769231";
                Session s = Session.getInstance(p, new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication(username, Password);
                    }
                });
                String from = username;
                String subject = "QUẦY THUỐC TÂY 99 ĐỔI MẬT KHẨU";
                String body = "Username: " + nv.getMaNV() + "\n"
                        + "Password: " + nv.getMatKhau();
                Message m = new MimeMessage(s);
                m.setFrom(new InternetAddress(from));
                m.setRecipients(Message.RecipientType.TO, InternetAddress.parse(email));
                m.setSubject(subject);
                m.setText(body);
                m.setSentDate(new Date());
                MimeBodyPart textpart = new MimeBodyPart();
                textpart.setContent(body, "text/plain");
                Multipart mp = new MimeMultipart();
                mp.addBodyPart(textpart);
                m.setContent(mp);
                Transport.send(m);
                MsgBox.alert(this, "Gửi mail thành công");
            } catch (Exception e) {
                MsgBox.alert(this, "Gửi mail thất bại");
            }
        }

    }
}
